# Generated by Django 3.2.8 on 2021-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.CharField(default='SOME ', max_length=1000),
        ),
    ]
