# Generated by Django 3.2.8 on 2021-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_auto_20211103_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=600)),
            ],
        ),
    ]
