# Generated by Django 3.2.8 on 2021-11-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='documento',
            field=models.FileField(default='SOME ', upload_to='noticias/'),
        ),
    ]
