# Generated by Django 3.2.8 on 2021-11-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_alter_noticia_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='documento',
            field=models.ImageField(upload_to='noticias'),
        ),
    ]
