# Generated by Django 3.2.8 on 2021-11-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0011_alter_noticia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha',
        ),
    ]
