# Generated by Django 3.2.8 on 2021-11-17 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0015_remove_noticia_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
