# Generated by Django 3.2.8 on 2021-11-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0016_noticia_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('ciclo', models.IntegerField(default=3)),
                ('foto', models.ImageField(upload_to='profesores')),
            ],
        ),
    ]
