# Generated by Django 3.2.8 on 2021-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0017_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='descripcion',
            field=models.CharField(default='profesor de educación básica', max_length=100),
        ),
    ]
