# Generated by Django 3.2.8 on 2021-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0019_profesor_universidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='redactor',
            field=models.CharField(default='Tomás Salgado', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
