# Generated by Django 3.2.8 on 2021-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0020_auto_20211206_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacado',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='noticia',
            name='lead',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tituloDestacado',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
