# Generated by Django 3.2.8 on 2022-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0021_auto_20211206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='documento',
            field=models.FileField(upload_to='noticias'),
        ),
    ]
