# Generated by Django 3.2.8 on 2022-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0024_alter_noticia_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('mision', models.CharField(max_length=200)),
                ('vision', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fono', models.CharField(max_length=200)),
                ('funciones', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='profesor',
            name='descripcion',
            field=models.CharField(default='profesor', max_length=100),
        ),
    ]
